INSERT INTO category (id, category) VALUES (1, 'Young adult fiction');
INSERT INTO category (id, category) VALUES (2, 'Science fiction');
INSERT INTO category (id, category) VALUES (3, 'Dystopia');
INSERT INTO category (id, category) VALUES (4, 'Romance');
INSERT INTO category (id, category) VALUES (5, 'Satire');
INSERT INTO category (id, category) VALUES (6, 'Tragedy');
INSERT INTO category (id, category) VALUES (7, 'Horror');
INSERT INTO category (id, category) VALUES (8, 'Fantasy');
INSERT INTO category (id, category) VALUES (9, 'Adventure');
INSERT INTO category (id, category) VALUES (10, 'Personal narrative');
INSERT INTO category (id, category) VALUES (11, 'Modernism');
INSERT INTO category (id, category) VALUES (12, 'Realism');
INSERT INTO book (id, isbn, title, author, published_year, price, quantity) VALUES (1, '9783883890227', 'The Catcher in the Rye', 'Jerome David Salinger', '1994', '19.50', 1);
INSERT INTO book_category (book_id, category_id) VALUES (1, 1);
INSERT INTO book_category (book_id, category_id) VALUES (1, 10);